Design Teardown - Microverse Project Submission
umairarshadbutt/Design-Teardown pull request #2
Opened 2020-06-19 16:50 UTC by umairarshadbutt

This pull request is for the clone of [Smashing Magazine ](https://www.smashingmagazine.com/)

2020-06-19 23:33 UTC, elmejdki commented
### Pull Request under review by @Zakariae

2020-06-19 23:53 UTC, elmejdki requested changes
# Great job so far guys you really got my attention :clap: :clap:, I think you made extras effort and features the project should be only a teardown of the original one but you made it as it is. good job :tophat: :tophat:, but in order to make your project approved you need to make some changes:

- Make the footer content smaller to fix this issue.
![image](https://user-images.githubusercontent.com/34653764/85186245-d9a8b080-b28f-11ea-9ab4-11a5f3334732.png)

- Validate your HTML in the [here](https://validator.w3.org/), while doing that I found a lot of errors:
![image](https://user-images.githubusercontent.com/34653764/85186332-4623af80-b290-11ea-830b-519d8b4d39ff.png)

### Please fix all the required changes before you submit another code review.
### :tophat: Happy Coding

2020-06-19 23:53 UTC, elmejdki commented on README.md
> +#Design Teardown
Add a space after the hash to allow markdown styling.

2020-06-19 23:53 UTC, elmejdki commented on index.html
> +            <div class="column4" >
Please use article tags here instead of div's for all the column4 classes

2020-06-20 07:57 UTC, umairarshadbutt commented on index.html
> +            <div class="column4" >
Done

2020-06-20 07:57 UTC, umairarshadbutt commented on README.md
> +#Design Teardown
Done

2020-06-20 08:06 UTC, elmejdki approved these changes
# Great job guys :clap: thanks for making the required changes
# status: approved 

You can now merge to master your project was approved.

### Happy Coding

2020-06-20 09:07 UTC, merged